hist(clean_data$price, breaks = 100, ylim = c(0, 800), main = "Histogram of Price")
hist(clean_data$cpuMark, breaks = 100, ylim = c(0, 400), main = "Histogram of CPU Mark")
hist(clean_data$threadMark, breaks = 100, ylim = c(0, 80), main = "Histogram of Thread Mark")
hist(clean_data$TDP, breaks = 100, ylim = c(0, 350), main = "Histogram of TDP")
hist(clean_data$powerPerf, breaks = 100)
plot(clean_data$price)
plot(clean_data$threadMark)
plot(clean_data$TDP)
plot(clean_data$powerPerf)
