hist(clean_data$price, breaks = 100)
hist(clean_data$cpuMark, breaks = 100)
hist(clean_data$threadMark, breaks = 100)
hist(clean_data$TDP, breaks = 100)
hist(clean_data$powerPerf, breaks = 100)
plot(clean_data$price)
plot(clean_data$threadMark)
plot(clean_data$TDP)
plot(clean_data$powerPerf)
